### ISSUE TITLE
th07: starting from resurrection butterfly spawns Yuyuko lower than it should

### ISSUE THREAD

**Issue by Priw8** [ack7139/thprac#1]
As the title says, Yuyuko's position is slightly wrong when starting from RB. It's noticable when you look at the laser position relative to lives and bombs on the HUD:
![thprac_rb](https://user-images.githubusercontent.com/44707079/84814626-094a8500-b012-11ea-8268-376fc42a368f.png)

By the way, I'm definitely looking forward to when you put the source code here :)

**Comment by ack7139** [comment]
Just tested it myself and seems to be the case. Thanks for the report, I'll upload the source code as soon as I can.

**Comment by ack7139** [comment]
Fixed in v1.9.4.2.
