### ISSUE TITLE
ddc vpatch

### ISSUE THREAD

**Issue by toimine** [ack7139/thprac#12]
somewhat recently a ddc vpatch got released yet thprac doesn't support it (it's on maribelhearn's site)

**Comment by ack7139** [comment]
Wow since when did that become a thing!? I'll add support in the next version.

**Comment by toimine** [comment]
Iirc 32th system made it on the trs server back in 2020 but it hasn't spread too far somehow

**Comment by ack7139** [comment]
Gotcha.

**Comment by Rika-TH** [comment]
seeing as this issue is still open, may aswell add that there is also vpatch on LoLK too (maribel's DL has had DDC for a while no clue when LoLK's was added and both ARE on shrine DLs)

**Comment by toimine** [comment]
Yo Ricco didn't know you had a github account
Lolk vpatch came out way before the ddc one, pretty sure thprac supports it

**Comment by ack7139** [comment]
Added in v2.0.6.2.
