### ISSUE TITLE
inaccuracy regarding wave timing on Shou's second nonspell

### ISSUE THREAD

**Issue by TheStarKing** [ack7139/thprac#14]
Normally, Shou first fires her second nonspell sometime during the 41st second of the timer.

![image](https://user-images.githubusercontent.com/80227332/110258604-740d6900-7f71-11eb-9778-f28537402d6e.png)

However, if you start on this nonspell using thprac, she first fires sometime during the 43rd second of the timer, while she still has invincibility.

![image](https://user-images.githubusercontent.com/80227332/110258628-91dace00-7f71-11eb-8bd6-0f825d83219e.png)

This is significant because you have 2 less seconds of damage in relation to the waves. For example, it becomes more difficult to end the nonspell before the 4th wave, due to having 2 less seconds of damage than you would normally at the time the wave comes. If you run to the corner on the 3rd wave (a common strategy) or are on 3 power, you probably won't be able to end it before the 4th wave on thprac, when normally you would be able to in those scenarios.

**Comment by ack7139** [comment]
In most cases, thprac skips the item drop process to save time, which causes nonspells to last a bit longer than the original. I'll either add an option that keeps item drops or just straight out shorten the nonspells' duration.

**Comment by ack7139** [comment]
Fixed in v2.0.6.
