### ISSUE TITLE
Can't link thprac shortcuts

### ISSUE THREAD

**Issue by inakilbss** [ack7139/thprac#15]
I generated the shortcuts, then ran the scan without even moving them. Despite pointing to the immediate folder they're in, it didn't find them.

**Comment by ack7139** [comment]
Can you post the shortcut here? (The shortcut itself, not the linked file)

**Comment by inakilbss** [comment]
(In a zip because GH doesn't allow .lnk)
[shortcut.zip](https://github.com/ack7139/thprac/files/6108958/shortcut.zip)

**Comment by ack7139** [comment]
Well yet another unfixable bug due to me can't replicate its behavior. I'll just ignore this for now until I implement a log system that allows further debug analysis.

**Comment by Alpha272** [comment]
Interestingly, the lnk from inakilbss works for me as well. I tried to create a link for myself, and mine doesn't work. I have no idea whats going on. My current workaround is to just throw the games into the thprac.json by hand, but obviously this is less than ideal. So yeeah.. You might wanna take a look at that. Hopefully you can replicate the bug with my file.

[th08.zip](https://github.com/ack7139/thprac/files/6413322/th08.zip)

**Comment by ack7139** [comment]
Closing because thcrap support is no longer based on shortcuts. Perfect.
