### ISSUE TITLE
[TH15]练习器能否再细分成单章节练习

### ISSUE THREAD

**Issue by monoko6** [ack7139/thprac#2]
就像无欠里的章节划分
如果可以的话希望能再单独分出三道中飞行阵，五道中【it's lunatic time】能有更加详细的章节练习

**Comment by ack7139** [comment]
已经安排上了，会有的

**Comment by monoko6** [comment]
> 就像无欠里的章节划分
> 如果可以的话希望能再单独分出三道中飞行阵，五道中【it's lunatic time】能有更加详细的章节练习
非常感谢

**Comment by ack7139** [comment]
已在v1.10.0中加入
