### ISSUE TITLE
UM only can be scanned if you select the modded option and it don't scan thcrap shortcuts

### ISSUE THREAD

**Issue by WilliamDavi** [ack7139/thprac#25]
For some reason UM only and be scanned if you select the modded option, and the thprac don't work if you put in the game directory

And thprac can't scan thcrap shortcuts, even then he find the .ink files.

**Comment by ack7139** [comment]
Only the dlsite version of the game will be recognized as original, and most game downloads available out there is just unpacked Steam version, so they will be treated as they were"modded'.
thcrap shortcuts support is a known bug that has been mentioned in another issue, so I'll close this one for now.
