### ISSUE TITLE
在中文系统下，如果东方红魔乡的文件名为"東方紅魔郷.exe"，则无法识别游戏

### ISSUE THREAD

**Issue by 63enjoy** [ack7139/thprac#26]
![99O8)EE$%FJY1L@2BYQGNL1](https://user-images.githubusercontent.com/44023015/117526858-7e43f600-affa-11eb-9bfb-aed3e364ef88.png)
目前可以通过修改thprac的exe里的字符串临时解决。

**Comment by ack7139** [comment]
Fixed in v2.0.6.1.
