### ISSUE TITLE
TH06

### ISSUE THREAD

**Issue by CHRISTXNE** [ack7139/thprac#3]
I read the readme about the TH06 issue but I still have no idea how to get it to work. 
I understand it has to do with changing the name of the Japanese .exe but when I do it opens an error box that's written in the same characters as what you said to change the exe to.
My original exe is written in kanji, is that why it doesn't work? I do have Locale installed (I'm a native English speaker).

**Comment by ack7139** [comment]
First make sure you have the Japanese version of game with the latest update (1.02h) installed. Rename the game's executable file to "東方紅魔鄉.exe", try again and if an error still pops, install [Locale Emulator](https://xupefei.github.io/Locale-Emulator/) and launch thprac with it. If you have no plan using the "Vsync patch", a simpler solution is to rename the game executable to "th06.exe".
