### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by GamingPiglet** [ack7139/thprac#32]
I was just doing a normal run through of EoSD easy mode (yes laugh) to see what I needed to work on, but when I got the ending, thprac got an exception. Here's the dump file.
[thprac-20210613-000345-0538.zip](https://github.com/ack7139/thprac/files/6643072/thprac-20210613-000345-0538.zip)

**Comment by ack7139** [comment]
Only dicks (and maybe Sakuya) mock people for playing easy mode. Anyway, about the exception, I've identified that this is a thcrap problem and created an issue: https://github.com/thpatch/thcrap/issues/144. I'll be closing this one since it's not related to thprac.
