### ISSUE TITLE
Practice tool doesn't work with TH6

### ISSUE THREAD

**Issue by Elola86** [ack7139/thprac#35]
Everytime I try to use the tool with EoSD, it always says that "No valid game was found", and it works perfectly with all the other games, this issue is just with 6

**Comment by ack7139** [comment]
Sorry for the late reply, apparently I missed this somehow. There's a great chance that you're not using the supported game version, or the game's executable has the wrong name. Check if the game is the original (Japanese) 1.02h version, and if it is, try to rename the game executable to "th06.exe" or "東方紅魔郷.exe".

**Comment by Elola86** [comment]
Thank you, but somehow the original Japanese version shows an error message everytime I try to open it while the english version works perfectly, so I don't think I'll be able to use the tool. 
Also, just out of curiosity, why does the tool work (at least for me) in the english version of every other Touhou game except for EoSD?

**Comment by ack7139** [comment]
DiffLocalization patches use

**Comment by ack7139** [comment]
Different localization patches use different methods to modify the game, and those who touch the game's script files are incompatible with thprac.
Speaking of that, are you using thcrap? It's a Touhou localization program that is known to be compatible with thprac, including EoSD.

**Comment by Elola86** [comment]
Yes, I'm using thcrap, that's why it's so weird that thprac only doesn't work with EoSD while it works perfectly with the others.
