### ISSUE TITLE
Could you make Excel sheet of PIV and score rate?

### ISSUE THREAD

**Issue by wefmaika** [ack7139/thprac#4]
We often make Excel sheet and research difference of PIV and score from point to point when we cannot reach target score If we go this way.
however, this work is very troublesome.
so, could you make function that if we push one key in seeing replay, this tool get PIV or score and write CSV file ?
(if this issue is hard to read, I'm sorry. this reason is that I'm Japanese and unfamiliar with Github)

**Comment by ack7139** [comment]
That seems easy to implement, could you provide a sample of what the csv file would look like? (So that I could have a reference)

**Comment by wefmaika** [comment]
We want output precise score, graze, and PIV in next row when trigger key is pushed like this image.
![_-pR521F](https://user-images.githubusercontent.com/62638744/88462239-ea7ac080-cee4-11ea-981c-6ed42650015f.png)
and I talk to an expert about this, he want graze, too.
so, I'm sorry for wrong with what I said before, could you write graze in the file?

**Comment by ack7139** [comment]
Of course. Thanks for the image, I'll implement this in the next version.

**Comment by wefmaika** [comment]
thanks!
we look forward to it!

**Comment by ack7139** [comment]
Implemented in v1.10.0 (you can see it by pressing F12).
