### ISSUE TITLE
风神录replay崩溃

### ISSUE THREAD

**Issue by sjh0020** [ack7139/thprac#42]
replay第五面
[thprac-20210920-103356-0828.zip](https://github.com/ack7139/thprac/files/7195080/thprac-20210920-103356-0828.zip)
崩溃

**Comment by ack7139** [comment]
请问崩溃发生的具体时间点是哪里？每次播放replay都会崩溃吗？
另外replay文件可否提供一下？

**Comment by sjh0020** [comment]
第五面开头开着thprac就崩
[th10_01.zip](https://github.com/ack7139/thprac/files/7196594/th10_01.zip)

**Comment by ack7139** [comment]
……首先thprac并不支持内置型汉化版游戏
其次这个replay似乎在任何版本的游戏下都无法正常播放，而且其记录的帧数极其怪异，目前只能认为是replay文件本身存在问题
