### ISSUE TITLE
光盘游戏无法识别

### ISSUE THREAD

**Issue by STARBOWBREAK6** [ack7139/thprac#51]
使用正版光盘setup.exe安装的东方无法被thprac识别
扫描结果为空
直接扫描光盘或是复制th**文件夹至本地扫描也无法识别
(本人使用从不同地方购买的3张光盘[星莲船、辉针城、绀珠传]测试，均未成功识别)
先启动游戏也无法识别进程注入

**Comment by ack7139** [comment]
thprac只能识别最新版本的游戏程序。
请在[此处](https://cloud.lilywhite.cc/s/4ZUW?path=%2F%E4%B8%9C%E6%96%B9Project%2F%E8%A1%A5%E4%B8%81%2F%E5%AE%98%E6%96%B9%E8%A1%A5%E4%B8%81)下载并应用对应游戏的最新升级补丁。（放置于游戏目录内执行即可）
