### ISSUE TITLE
IN practice crash

### ISSUE THREAD

**Issue by Dimmitsaras** [ack7139/thprac#60]
Magic team, hard, warp to 6b end boss final spell Divine Treasure "jeweled branch of hourai -dreamlike paradise-" . Crashes on restart (esc + r)
[crashdump.zip](https://github.com/ack7139/thprac/files/7881294/crashdump.zip)
)

**Comment by ack7139** [comment]
The crash happened in vcruntime140.dll, a dynamic library that neither thprac nor the original game uses. What other things did you use along with thprac?
I'm closing this for now because it's unrelated to thprac, but you can still reply here so I may help you to identify the problem.

**Comment by Dimmitsaras** [comment]
Thprac is somehow the thing that pops up the error and halts the game though https://i.imgur.com/RvYhBRb.png (turns out the warp location doesnt matter). Its why i was able to find where to get the dump files.

There's no vcruntime140.dll in my th folder, im using thcrap and the vpatch that goes along with it. I launch the game using that then apply thprac while the game is running.

I tried to replicate the issue by launching the game with thprac alone and i could not. Its most likely a compatibility issue.

It's my first time trying to read a dump file but could it be that thprac tries to read from an address that vcruntime uses? Can't imagine how else it would be involved.

Thanks for the help and for the amazing practice tool, since I found a workaround don't spend too much time on it.

**Comment by ack7139** [comment]
Something I screwed up is that the error prompt is a bit misleading. When a crash happens, no matter if it's related to thprac or not, the prompt will jump out and implies that thprac is the culprit to blame for, which is simply not true in quite a few cases, including this one.
So what happened here is that something else that invoked vcruntime140.dll caused the crash, but thprac picked it up and reported it instead.
It may very well be some kind of wicked compatibility issue like you've mentioned. I'll inspect the dump file more closely when I have time and see if I can fix this on my side.
