### ISSUE TITLE
Stage portion selection missing in th10 st4

### ISSUE THREAD

**Issue by Priw8** [ack7139/thprac#7]
![th10](https://user-images.githubusercontent.com/44707079/96289351-2f465d00-0fe5-11eb-8a11-a9f9f7dcd79b.PNG)
It's possible to select the "stage portion" option, but the slider for selecting the actual portion is missing. This happens only with stage 4, the slider appears correctly for all other stages in th10. Is there a reason for that, or is it a bug?

**Comment by ack7139** [comment]
It was a PITA to do stage 4 and I just skipped it. Will fix it in the next release.

**Comment by Priw8** [comment]
Understandable, I looked at stage 4 ECL and it looks really weird compared to more recent games

**Comment by ack7139** [comment]
Fixed in v1.10.1.
