### ISSUE TITLE
thprac v2.0.2 doesnt work under WINE in Arch Linux

### ISSUE THREAD

**Issue by Kho-Dialga** [ack7139/thprac#9]
I've been having issues running this under my Linux install with wine 5.22. What's weird is that older versions of thprac worked properly.

Here's the backtrace.txt that WINE gives.
[backtrace.txt](https://github.com/ack7139/thprac/files/5698863/backtrace.txt)

**Comment by Kho-Dialga** [comment]
Nevermind, i was using the standard wine package. I just needed to change to the wine-staging package. I'll be closing this issue now.

**Comment by ack7139** [comment]
Just checked and this is actually not wine's problem. thprac is badly-coded to use only Windows' proprietary fonts and will very likely to crash if they're not found. wine-staging probably has some specific code that deals with this kind of situation as it's actually quite common. I'll keep this issue closed but also implement a sensible solution in the future.
